# Generated by Django 4.0.6 on 2023-01-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DDD',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.IntegerField(max_length=2, verbose_name='DDD')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'DDDs',
            },
        ),
    ]
