# Generated by Django 4.0.6 on 2023-01-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_ddd_ddd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddd',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
